In [ ]:
# Install the jovian Python library
!pip install jovian --upgrade -q

# Tensor Operations
## List of few interesting yet useful functions used in PyTorch
### PyTorch is a library based on Python that is used to optimize tensor manipulations. Few advantages to use PyTorch include its array of packages used for deep learning, python support and dynamic computation graphs.
##### 1. torch.reshape()
##### 2. torch.unsqueeze()
##### 3. torch.mm()
##### 4. torch.mul()
##### 5. torch.cross()

In [1]:
import jovian
import torch

<IPython.core.display.Javascript object>

In [2]:
def describe(x):
    print("Type:       {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values:\n {}".format(x))

## Funtion 1 - torch.reshape(input, shape) -> tensor

reshape() was introduced in version 0.4 . It returns a tensor with the
same data as input but with a specified shape. When we use torch.reshape(),
the new tensor could be a view of the orignal tensor or it could be a new tensor. 

In [3]:
# Example 1: working
a = torch.rand(3, 4)
describe(a)
a.reshape(6, 2)

Type:       torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values:
 tensor([[0.3639, 0.2020, 0.3837, 0.4622],
        [0.8334, 0.9769, 0.1666, 0.9551],
        [0.5527, 0.0371, 0.2782, 0.1400]])


tensor([[0.3639, 0.2020],
        [0.3837, 0.4622],
        [0.8334, 0.9769],
        [0.1666, 0.9551],
        [0.5527, 0.0371],
        [0.2782, 0.1400]])

In the above example, it can be noticed that we can specify the row x column shape of our want.


It should be noted that product of all the shapes need to be same as total number of elements in the tensor.

In [4]:
# Example 2: working
a.reshape(3, 1, 4)

tensor([[[0.3639, 0.2020, 0.3837, 0.4622]],

        [[0.8334, 0.9769, 0.1666, 0.9551]],

        [[0.5527, 0.0371, 0.2782, 0.1400]]])

In the second example, the rank of the tensor is increased to 4. There are 3 channels, where each row has 4 columns.

In [5]:
# Example 3: breaking point
a.reshape(4, 2, 2)

RuntimeError: shape '[4, 2, 2]' is invalid for input of size 12

As mentioned earlier that the product of shapes must be equal to the number of elements in the tensor, otherwise, we will encounter a runtime error.

## Function 2 - torch.unsqeeze(input, dim) -> tensor
unsqueeze() returns a tensor after adding a dimension of length one at a specified position.
It shares the same data as the orignal tensor

In [6]:
# Example 1: working
a = torch.rand(3)
describe(a)
describe(torch.unsqueeze(a, 0))

Type:       torch.FloatTensor
Shape/size: torch.Size([3])
Values:
 tensor([0.3595, 0.4733, 0.5840])
Type:       torch.FloatTensor
Shape/size: torch.Size([1, 3])
Values:
 tensor([[0.3595, 0.4733, 0.5840]])


In the above example, we have added a new dimension at position zero.

In [7]:
describe(torch.unsqueeze(a, 1))

Type:       torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values:
 tensor([[0.3595],
        [0.4733],
        [0.5840]])


In example 2, a new dimension is added at position 1.

In [8]:
b = torch.rand(2,3)
describe(b)
describe(torch.unsqueeze(b, 3))

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[0.7627, 0.3160, 0.7986],
        [0.4636, 0.0492, 0.1258]])


IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

the tensor in b is 2 dimensional with the shape of ([2, 2]). So if you add an additional dimension at position 0, 
the resultant shape will be (1, 2, 2), and for adding a dimension at 1 and 2 position, the resulting shape will
be ([2,1,2]), ([2,2,1]) respectively. In example 3, an IndexError occurs because dimension is out of range. 
The range is calculated by [-input.dim() - 1, input.dim() + 1)

## Function 3 - torch.mm(input, other) -> tensor
The mm() preforms matrix multiplication of two matrices.
The matrix1 tensor is (n, m) shape, matrix2 is of (m, p) shape and output tensor will be (n, p) shape

In [9]:
# Example 1: working
a = torch.rand(2, 4)
b = torch.rand(4, 3)
describe(a)
print("====================================")
describe(b)
print("====================================")
describe(torch.mm(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values:
 tensor([[0.7245, 0.0418, 0.7495, 0.5198],
        [0.6651, 0.8343, 0.5346, 0.5054]])
Type:       torch.FloatTensor
Shape/size: torch.Size([4, 3])
Values:
 tensor([[0.6612, 0.0372, 0.8452],
        [0.8726, 0.9716, 0.2240],
        [0.4842, 0.4053, 0.0668],
        [0.1179, 0.6183, 0.3120]])
Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[0.9397, 0.6927, 0.8340],
        [1.4862, 1.3645, 0.9424]])


In the first example, two tensors a, b with the shape ([2, 4]), ([4, 3]) are created respectively. mm() multiplies two matrices and returns tensor with the shape of ([2, 3]).

In [10]:
# Example 2: working
a = torch.rand(1, 4)
describe(a)
print("====================================")
b = torch.ones(4, 2)
describe(b)
print("====================================")
describe(torch.mm(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([1, 4])
Values:
 tensor([[0.9123, 0.6377, 0.2002, 0.7896]])
Type:       torch.FloatTensor
Shape/size: torch.Size([4, 2])
Values:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
Type:       torch.FloatTensor
Shape/size: torch.Size([1, 2])
Values:
 tensor([[2.5398, 2.5398]])


The second example is similar to first example, where the resulting matrix has a shape of ([1, 2]).

In [11]:
# Example 3: breaking point
x = torch.rand(0)
y = torch.rand(2, 3)
describe(torch.mm(x, y))

RuntimeError: matrices expected, got 1D, 2D tensors at C:\w\1\s\tmp_conda_3.7_100118\conda\conda-bld\pytorch_1579082551706\work\aten\src\TH/generic/THTensorMath.cpp:131

matrix multiplication using mm() in pytorch does'nt work on matrices that are not bradcastable. 
In third example, a and b are not broadcastable, because a does not have atleast 1 dimension.

## Function 4 - torch.mul(input, other) -> tensor
The function torch.mul() performs the element-wise multiplication of two tensors.

In [12]:
a = torch.tensor([[[ 0., 1., 2.],
                   [ 3., 4., 5.]]])
describe(a)
print("====================================")
b = torch.rand(1, 3)
describe(b)
print("====================================")
describe(torch.mul(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([1, 2, 3])
Values:
 tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
Type:       torch.FloatTensor
Shape/size: torch.Size([1, 3])
Values:
 tensor([[0.5282, 0.2708, 0.5079]])
Type:       torch.FloatTensor
Shape/size: torch.Size([1, 2, 3])
Values:
 tensor([[[0.0000, 0.2708, 1.0159],
         [1.5846, 1.0830, 2.5397]]])


In the aforementioned example, we perform element wise matrix multiplication between tensors a , b. 

In [13]:
a = torch.rand(2, 3)
describe(a)
print("====================================")
b = 100
print("====================================")
describe(torch.mul(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[0.8370, 0.7273, 0.2861],
        [0.7734, 0.7017, 0.4191]])
Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[83.7022, 72.7301, 28.6087],
        [77.3449, 70.1695, 41.9115]])


As show in the second example, elementwise multiplication is performed where, matrix a is a FloatTensor, it could also be a DoubleTensor and the matrix b is an integer, it can also be any real number.

In [14]:
# Example 3: Breaking point
a = torch.tensor([[[1, 2, 3],
  [4, 5, 6]]])
describe(a)
print("====================================")
b = torch.tensor([[1, 1, 1],
 [2, 2, 2],
 [3, 3, 3]])
describe(b)
print("====================================")
describe(torch.mul(a, b))

Type:       torch.LongTensor
Shape/size: torch.Size([1, 2, 3])
Values:
 tensor([[[1, 2, 3],
         [4, 5, 6]]])
Type:       torch.LongTensor
Shape/size: torch.Size([3, 3])
Values:
 tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

After executing the third example cell, we encounter an error because the dimensions of two matrices must be equal i.e. broadcastable. 

## Function 5 - torch.cross(matrix1, matrix2, dim = -1, out) -> tensor
cross() returns cross product of vectors in dimension of matrix1 and matrix2.

In [15]:
# Example 1: Working
a = torch.tensor([[0. , 1. , 2.],
                 [3. , 4. , 5.]])
b = torch.tensor([[6., 7. , 8.],
                  [9., 10. , 11.]])
describe(a)
describe(b)
torch.cross(a, b)

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[0., 1., 2.],
        [3., 4., 5.]])
Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])


tensor([[-6., 12., -6.],
        [-6., 12., -6.]])

As shown above, cross() creates a tensor with the result of cross product between two matrices a and b
with the shapes of ([2, 3])

In [16]:
# Example 2: Working
a = torch.rand(2, 3)
b = torch.rand(2, 3)
describe(torch.cross(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values:
 tensor([[ 0.2770, -0.4374,  0.4432],
        [-0.0979,  0.0179,  0.0294]])


Similar to example 1, cross product is performed on two matrices with random real numbers. 

In [17]:
# Example 3: Breaking point
a = torch.tensor([[0. , 1. , 2., 3.],
                 [4. , 5. , 6., 7.]])
b = torch.tensor([[8., 9. , 10. , 11.],
                  [12., 13. , 14. , 15.]])
describe(a)
describe(b)
describe(torch.cross(a, b))

Type:       torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values:
 tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])
Type:       torch.FloatTensor
Shape/size: torch.Size([2, 4])
Values:
 tensor([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


RuntimeError: no dimension of size 3 in input

We come accross RuntimeError in third example, this is due to the reason that the dimensions of the a and b tensors do'nt match. It is important to note that matrix1 and matrix2 must have the same size, and the size of their dimension
must be 3.

# Conclusion
In this notebook, we explored 5 of many interesting and usefull functions to work with tensors using pytorch. We understood the defination and working of the functions with working examples and also came accross errors some examples  because it is also important to know when those functions would'nt work. 

Thank You very much!

# Reference Links
1. Official documentation for torch.Tensor: https://pytorch.org/docs/stable/tensors.html
2. Tensors For Deep Learning With PyTorch: https://deeplizard.com/learn/video/fCVuiW9AFzY

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "harsh-hr305/pytorch-assignment" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/harsh-hr305/pytorch-assignment


'https://jovian.ml/harsh-hr305/pytorch-assignment'